name: "Publish to Maven Repository"
on:
  workflow_dispatch:
  push:
    branches:
      - main
    tags:
      - '*'

jobs:
  publish-maven:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'corretto'
          cache: maven
      - name: Publish to Maven Repository
        run: mvn -B -U -DskipTests=true clean source:jar deploy
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}